image_size: 112
embedding_size: 512
checkpoint: /hdd/minhdq/insightface/recognition/checkpoints/face_reg-02/mymodel-84
database: database.pickle
filenames: filename.pickle
threshold: 0.4
web_service:
  ip: '192.168.0.104'
  port: 74123